# Generated by Django 2.1.14 on 2020-09-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('link', models.URLField(default='')),
                ('comment', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ReadPosts',
            new_name='ReadPost',
        ),
        migrations.AddField(
            model_name='use',
            name='category',
            field=models.CharField(choices=[['Development', 'Development'], ['Productivity', 'Productivity'], ['Equipment', 'Equipment']], default='', max_length=500),
        ),
    ]
