# Generated by Django 2.1.14 on 2020-09-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200906_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='use',
            name='category',
            field=models.TextField(default=''),
        ),
    ]
