# Generated by Django 2.1.14 on 2020-09-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200906_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
