# Generated by Django 2.1.14 on 2020-09-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200906_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='category',
            field=models.TextField(choices=[['Development', 'Development'], ['Productivity', 'Productivity'], ['Equipment', 'Equipment']], default=''),
        ),
    ]
