# Generated by Django 2.1.14 on 2020-09-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200906_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
