# Generated by Django 2.1.14 on 2020-09-06 19:03

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200906_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
