# Generated by Django 3.0.9 on 2020-10-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_file_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='uploadedfile',
        ),
    ]
